name: Deploy to Heroku

# Trigger the action on push to the master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to the Heroku Container Registry using the Heroku API key
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      # Step 3: Build the Docker image for the Heroku app
      - name: Build Docker image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      # Step 4: Push the Docker image to Heroku Container Registry
      - name: Push Docker image to Heroku
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Step 5: Release the Docker image on Heroku
      - name: Release the Docker image to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      # Step 6: (Optional) Check the status of the app
      - name: Check Heroku app status
        run: |
          heroku ps --app ${{ secrets.HEROKU_APP_NAME }}
